---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Tap Homebrew repositories, state present
  community.general.homebrew_tap:
    name:
      - homebrew/cask
    state: present

- name: Install CUI applications using Homebrew
  community.general.homebrew:
    name:
      - asdf
      - fzf
      - peco
      - gh
      - ghq
      - jq
      - mas
    state: present

- name: Install GUI applications using Homebrew Cask
  community.general.homebrew:
    name:
      - alfred
      - docker
      - karabiner-elements
      - google-chrome
      - wezterm
      - discord
      - slack
      - visual-studio-code
      - zoom
      - webex-meetings
    state: present
