---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Tap homebrew/cask, state present
  community.general.homebrew_tap:
    name:
      - homebrew/cask
      - jesseduffield/lazygit
    state: present

- name: Install CUI applications using Homebrew
  community.general.homebrew:
    name:
      - mise
      - neovim
      - lazygit
      - fzf
      - peco
      - gh
      - ghq
      - jq
      - mas
      - go
      - deno
    state: present
    path: "/opt/homebrew/bin:/usr/local/bin"

- name: Install GUI applications using Homebrew Cask
  community.general.homebrew_cask:
    name:
      - neovide
      - raycast
      - rectangle
      - docker
      - jetbrains-toolbox
      - google-chrome
      - wezterm
      - discord
      - slack
      - gitify
      - visual-studio-code
      - vlc
      - gimp
      - inkscape
      - spotify
    state: present
    path: "/opt/homebrew/bin:/usr/local/bin"

- name: (sudo) Install GUI applications using Homebrew Cask
  community.general.homebrew_cask:
    name:
      - karabiner-elements
      - google-drive
    state: present
    path: "/opt/homebrew/bin:/usr/local/bin"
    sudo_password: "{{ ansible_become_pass }}"

# - name: Install App Store applications
#   community.general.mas:
#     id:
#       - 409183694 # Keynote
#     state: present
