---
- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Tap homebrew/cask, state present
  community.general.homebrew_tap:
    name:
      - homebrew/cask
      - jesseduffield/lazygit
    state: present

- name: Install CUI applications using Homebrew
  community.general.homebrew:
    name:
      - asdf
      - neovim
      - lazygit
      - fzf
      - peco
      - gh
      - ghq
      - jq
      - mas
    state: present

- name: Install GUI applications using Homebrew Cask
  community.general.homebrew_cask:
    name:
      - raycast
      - docker
      - jetbrains-toolbox
      - google-chrome
      - wezterm
      - iterm2
      - discord
      - slack
      - gitify
      - visual-studio-code
      - vlc
      - gimp
      - inkscape
      - zotero
      - spotify
    state: present

- name: (sudo) Install GUI applications using Homebrew Cask
  community.general.homebrew_cask:
    name:
      - zoom
      - karabiner-elements
      - webex-meetings
      - google-drive
      - google-japanese-ime
    state: present
    sudo_password: "{{ ansible_become_pass }}"

- name: Install App Store applications
  community.general.mas:
    id:
      - 409183694 # Keynote
    state: present
