---
# Dock
- name: Enable autohide for dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: int
    value: 1
    state: present

- name: Dock appears instantly
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    state: present

# Keyboard
- name: KeyRepeat immediately
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present

# Trackpad
- name: KeyRepeat quickly
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Enable tap as click
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    type: int
    value: 1
    state: present

# External mouse
- name: Enable TwoButton Mode
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchMouse
    key: MouseButtonMode
    type: string
    value: TwoButton
    state: present

- name: Disable mouse scaling
  community.general.osx_defaults:
    domain: "Apple Global Domain"
    key: com.apple.mouse.scaling
    type: float
    value: -1
    state: present
